Debug=true
# Set how frequently to update the UI (in milliseconds - 1000ms equals 1 second)
UpdateInterval=150
# Temperature units - `C` or `c` for Celsius, `F` or `f` for Fahrenheit
TempScale="f"

#
EnableUIButtons=true

# Enable or disable gpu/nvidia tracking
EnableNvidia=true

# (true or false) Enable or disable grouping of processes in Processes table
GroupProcesses=false
ShowOnlyUserProcesses=false

# Format memory values in the Processes table as Percent instead of in Gigabytes
#FormatMemoryAsPercent=true

# Set network IO to mbps if true
#mbps=false

### DEBUG AREA  ################################################################
# Overrides the selected view. (<=-1 or 0 for default view - this is usually used for debugging)
SelectedViewOverride=0
